name: Contributors

# Update the contributors list in the documentation monthly
# or manually using the contributors-readme-action GitHub Action
# on the default branch main.
# As the branch is protected, the action will create a pull request.
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month
  workflow_dispatch:

jobs:
  update_contributors_list:
    name: Update Contributors List
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: docs/source/community/people.md
          pr_title_on_protected: 'Contributors-Readme-Action: Update contributors list'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
